/**
 * Accounts Table Schema
 *
 * OAuth and credential accounts for the Chat with Google Maps application.
 * Links authentication providers to users, supporting both email/password
 * and OAuth providers (Google, GitHub, etc.).
 *
 * Required by Better Auth for provider account management.
 *
 * @module api/_db/schema/accounts
 */

import { pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { users } from './users.ts';

/**
 * Accounts table definition
 *
 * Fields:
 * - id: Text primary key (UUID string, generated by application)
 * - userId: Foreign key reference to users table (cascade delete)
 * - accountId: Provider's unique account identifier
 * - providerId: Authentication provider name (e.g., 'credential', 'google')
 * - accessToken: OAuth access token (optional, for OAuth providers)
 * - refreshToken: OAuth refresh token (optional, for OAuth providers)
 * - accessTokenExpiresAt: Access token expiration (optional)
 * - refreshTokenExpiresAt: Refresh token expiration (optional)
 * - scope: OAuth scopes granted (optional)
 * - idToken: OpenID Connect ID token (optional)
 * - password: Hashed password (for credential provider only)
 * - createdAt: Record creation timestamp
 * - updatedAt: Record last update timestamp
 */
export const accounts = pgTable('accounts', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  accessTokenExpiresAt: timestamp('access_token_expires_at'),
  refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
  scope: text('scope'),
  idToken: text('id_token'),
  password: text('password'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

/** Account type inferred from select operations */
export type Account = typeof accounts.$inferSelect;

/** NewAccount type inferred from insert operations */
export type NewAccount = typeof accounts.$inferInsert;
