/**
 * Sessions Table Schema
 *
 * Auth-ready sessions table for the Chat with Google Maps application.
 * Designed to be compatible with Better Auth expected structure.
 *
 * @module api/_db/schema/sessions
 */

import { pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { users } from './users.ts';

/**
 * Sessions table definition
 *
 * Fields:
 * - id: Text primary key (UUID string, generated by application)
 * - userId: Foreign key reference to users table (cascade delete)
 * - expiresAt: Session expiration timestamp
 * - createdAt: Record creation timestamp
 */
export const sessions = pgTable('sessions', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

/** Session type inferred from select operations */
export type Session = typeof sessions.$inferSelect;

/** NewSession type inferred from insert operations */
export type NewSession = typeof sessions.$inferInsert;
