/**
 * Sessions Table Schema
 *
 * Auth-ready sessions table for the Chat with Google Maps application.
 * Designed to be compatible with Better Auth expected structure.
 *
 * @module api/_db/schema/sessions
 */

import { pgTable, text, timestamp, index } from 'drizzle-orm/pg-core';
import { users } from './users.ts';

/**
 * Sessions table definition
 *
 * Fields:
 * - id: Text primary key (UUID string, generated by application)
 * - token: Unique session token for authentication (required by Better Auth)
 * - userId: Foreign key reference to users table (cascade delete)
 * - expiresAt: Session expiration timestamp
 * - ipAddress: Client IP address (optional)
 * - userAgent: Client user agent string (optional)
 * - createdAt: Record creation timestamp
 * - updatedAt: Record last update timestamp
 */
export const sessions = pgTable(
  'sessions',
  {
    id: text('id').primaryKey(),
    token: text('token').notNull().unique(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    expiresAt: timestamp('expires_at').notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  table => [index('sessions_user_id_idx').on(table.userId)]
);

/** Session type inferred from select operations */
export type Session = typeof sessions.$inferSelect;

/** NewSession type inferred from insert operations */
export type NewSession = typeof sessions.$inferInsert;
