/**
 * Users Table Schema
 *
 * Auth-ready users table for the Chat with Google Maps application.
 * Designed to be compatible with Better Auth expected structure.
 *
 * @module api/_db/schema/users
 */

import { pgTable, text, timestamp, boolean } from 'drizzle-orm/pg-core';

/**
 * Users table definition
 *
 * Fields:
 * - id: Text primary key (UUID string, generated by application)
 * - email: User email address (unique, required)
 * - emailVerified: Whether email has been verified (default false)
 * - name: User display name (optional)
 * - image: User profile image URL (optional)
 * - createdAt: Record creation timestamp
 * - updatedAt: Record last update timestamp
 */
export const users = pgTable('users', {
  id: text('id').primaryKey(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').default(false),
  name: text('name'),
  image: text('image'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

/** User type inferred from select operations */
export type User = typeof users.$inferSelect;

/** NewUser type inferred from insert operations */
export type NewUser = typeof users.$inferInsert;
