/**
 * Verifications Table Schema
 *
 * Verification tokens for the Chat with Google Maps application.
 * Stores tokens for email verification, password reset, and other
 * verification flows.
 *
 * Required by Better Auth for verification token management.
 *
 * @module api/_db/schema/verifications
 */

import { pgTable, text, timestamp } from 'drizzle-orm/pg-core';

/**
 * Verifications table definition
 *
 * Fields:
 * - id: Text primary key (UUID string, generated by application)
 * - identifier: The entity being verified (typically email address)
 * - value: The verification token or code
 * - expiresAt: Token expiration timestamp
 * - createdAt: Record creation timestamp
 * - updatedAt: Record last update timestamp
 */
export const verifications = pgTable('verifications', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

/** Verification type inferred from select operations */
export type Verification = typeof verifications.$inferSelect;

/** NewVerification type inferred from insert operations */
export type NewVerification = typeof verifications.$inferInsert;
